name: plibsys-ci
on: [push, pull_request]
jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            CC: gcc
            CXX: g++
          - os: ubuntu-latest
            CC: clang
            CXX: clang++
          - os: macos-latest
            CC: clang
            CXX: clang++
          - os: macos-latest
            CC: gcc-12
            CXX: g++-12
    steps:
      - uses: actions/checkout@v3
      - name: config
        run: |
          pwd
          cd ..
          mkdir ./plibsys-build
          cd ./plibsys-build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.CC }} -DCMAKE_CXX_COMPILER=${{ matrix.CXX }} -DPLIBSYS_COVERAGE=ON ../plibsys
      - name: build
        run: |
          pwd
          cd ../plibsys-build
          make -j
      - name: test
        run: |
          pwd
          cd ../plibsys-build
          ctest
      - name: coverage-install
        if: ${{ success() && startsWith(${{ matrix.CC }}, 'gcc' }}
        run: |
          pwd
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get update
              sudo apt-get install lcov
          elif [ "$RUNNER_OS" == "macOS" ]; then
              brew update
              brew install lcov
          else
              echo "Unknown operating system of runner"
              exit 1
          fi
          pip install codecov-cli
          echo "CODECOV_OS=${RUNNER_OS,,}" >> ${GITHUB_ENV}
      - name: coverage-run
        if: ${{ success() && startsWith(${{ matrix.CC }}, 'gcc' }}
        run: |
          pwd
          codecovcli create-commit -t ${{ secrets.CODECOV_TOKEN }}
          lcov -c --directory ../plibsys-build --no-external --base-directory . --output-file ../plibsys-build/coverage.info
          codecovcli -v create-report -t ${{ secrets.CODECOV_TOKEN }}
          codecovcli -v do-upload --dir ../plibsys-build --name github-${{ env.CODECOV_OS }} -t ${{ secrets.CODECOV_TOKEN }}
