name: plibsys-ci
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: config
        run: |
          pwd
          cd ..
          mkdir ./plibsys-build
          cd ./plibsys-build
          cmake -DCMAKE_BUILD_TYPE=Release ../plibsys
      - name: build
        run: |
          pwd
          cd ../plibsys-build
          make -j
      - name: test
        run: |
          pwd
          cd ../plibsys-build
          ctest
